[tool.poetry]
name = "my-diary"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.2.1"
gunicorn = "^23.0.0"
psycopg2-binary = "^2.9.10"
markdown = "^3.8"
redis = "^6.1.0"
celery = "^5.5.2"
python-decouple = "^3.8"
django-crispy-forms = "^2.4"
crispy-bootstrap5 = "^2025.4"
black = "^25.1.0"
flake8 = "^7.2.0"
load-dotenv = "^0.1.0"
dotenv = "^0.9.9"
docker = "^7.1.0"
markdownify = "^1.1.0"
pillow = "^11.2.1"
django-markdownify = "^0.9.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
